name: very_good_dropdown_search
description: A Dropdown search widget with uses a text filed as its search bar.
version: 0.0.1+1
homepage: https://github.com/tomassasovsky/very_good_dropdown_search

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
